dist: focal
language: cpp
env:
  - NODE_VERSION="12"
  - NODE_VERSION="14"
  - NODE_VERSION="16"
sudo: false
cache:
  directories:
    - node_modules
    - ~/.clangd
scripts:
  - set -e
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - if [[ ! -d ~/.clang ]]; then
      rm -rf ~/.configs
      && git clone https://github.com/dragoscirjan/configs --branch v2 .configs
      && (cd .configs/lang && make clang CLANG_FOLDER=~/.clang);
    fi
  - PATH="`find ~/.clang -mindepth 1 -maxdepth 1 -type d -iname 'clang*'`/bin:$PATH"
  - node --version
  - npm --version
  - clang-format --version
  - python --version
  - $CXX --version
  - npm install
  - npm run ca
  - npm run test
  - npm run build
after_script:
  - "if [[ $TRAVIS_NODE_VERSION == '14' && $TRAVIS_OS_NAME == 'linux' ]]; then
      npm run docs;
    fi # sonar-scanner;"
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
# addons:
#   sonarcloud:
#     organization: "templ-project"
#     token:
#       secure: r5HrVIMWtNhWKJAKViREyARl3UAHDfJreL0oLTxzY/isOvcDTHMr3xbx+nCJIIKRacVpamDm91oZv1KW16V9ZFL1h/vEobzjxyt4bPoHZHukLj+UvV4QvVJsAgZBAQsjBo75JtDPFhWAHgQOosWkx3u41RMGRNOP7QlOoO3CaJwynN5uhyOvKJ2KtjNNVjiBf0rM0x/qfrKtV9LXN8C+6tTK2/YesvR1jJYzTCYi+fgLNfSqz9pOs5AwrnEWQIBpyDwICTTgZOt55dGbQWVUhg2I8b+XjvVso5K1B8ovbNYBICVvf6EUnHne5uoa0h9FrJPbsp9g1tktnFBscQMV8Pi9wX4A/FE8SZzPR9JH3t5Udm6MeKKBwz4q1CJF20BYMnTaMUy/GZtpN2fI0Pnq34VOAwQLzWuY9idM+AYlbmES2TbDH0MDcM/R5d38fCa8Z5MrQjDAD500K/kx1zJFh00N+G+BiQDape6+MhxfpwwZpc6CGXpb5feBJn06iglv0Fjqr2ux4tzjuH5pV342S8mtya4l5GP31P5Vs/nvwdgIlb1ucNcM7oN6Gwu8yWPUgBQXxapPybUEaDpVCIpcIX3n5g/SUXVOHjCyOqJfGv2+LEdKWA+v7WsKRsJfA7F+867dBkOoDQy3CXiRWj7tZiIShzkCZaB6Om6ZIGeXJYM=
