#! /bin/bash

OS=$(uname)

CLANG_VERSION="12.0.0"
if [ "$OS" != "Darwin" ]; then
  OS_ARCH=$(uname -m)
  OS_ID=$(cat /etc/*-release | egrep "^ID=" | awk -F '=' '{print $2}')
  VERSION_ID=$(cat /etc/*-release | egrep "VERSION_ID=" | awk -F '=' '{print $2}' | awk -F '"' '{print $2}')
  URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-$CLANG_VERSION/clang+llvm-$CLANG_VERSION-$OS_ARCH-linux-gnu-$OS_ID-$VERSION_ID.tar.xz"
else
  URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-$CLANG_VERSION/clang+llvm-$CLANG_VERSION-x86_64-apple-darwin.tar.xz"
fi

curl -SL "$URL" --output .scripts/clang.tar.xz

tar -xf .scripts/clang.tar.xz -C .scripts --checkpoint=.10000
mv .scripts/clang+* .scripts/clang

rm .scripts/clang.tar.xz
