#! /bin/bash
set -xe

CLANG="clang-format --verbose -style=file $@"

FILTER="-iname *.c"

for ext in cc cpp h; do FILTER="$FILTER -or -iname *.$ext"; done

# pwd

find ./src $FILTER | while read f; do $CLANG $f; done


